# Generated by Django 5.1.5 on 2025-01-16 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finsafe_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='member',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='member',
        ),
        migrations.DeleteModel(
            name='Deposit',
        ),
        migrations.DeleteModel(
            name='Loan',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
