# Generated by Django 5.1.5 on 2025-01-21 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finsafe_app', '0019_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='member',
        ),
        migrations.RemoveField(
            model_name='group',
            name='members',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='group',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='member',
        ),
        migrations.RemoveField(
            model_name='member',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='member',
        ),
        migrations.RemoveField(
            model_name='withdraw',
            name='member',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='user',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Deposit',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Loan',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='Withdraw',
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
    ]
